/********************************************************************
* GUIwrapperCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GUIwrapperCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGUIwrapperCint();
extern void G__cpp_setup_inheritanceGUIwrapperCint();
extern void G__cpp_setup_typetableGUIwrapperCint();
extern void G__cpp_setup_memvarGUIwrapperCint();
extern void G__cpp_setup_globalGUIwrapperCint();
extern void G__cpp_setup_memfuncGUIwrapperCint();
extern void G__cpp_setup_funcGUIwrapperCint();
extern void G__set_cpp_environmentGUIwrapperCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GUIwrapper.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GUIwrapperCintLN_TClass;
extern G__linked_taginfo G__GUIwrapperCintLN_TBuffer;
extern G__linked_taginfo G__GUIwrapperCintLN_TMemberInspector;
extern G__linked_taginfo G__GUIwrapperCintLN_TObject;
extern G__linked_taginfo G__GUIwrapperCintLN_TString;
extern G__linked_taginfo G__GUIwrapperCintLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__GUIwrapperCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GUIwrapperCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GUIwrapperCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GUIwrapperCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GUIwrapperCintLN_TGObject;
extern G__linked_taginfo G__GUIwrapperCintLN_TQObject;
extern G__linked_taginfo G__GUIwrapperCintLN_TGWindow;
extern G__linked_taginfo G__GUIwrapperCintLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GUIwrapperCintLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GUIwrapperCintLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GUIwrapperCintLN_TGFrame;
extern G__linked_taginfo G__GUIwrapperCintLN_TGCompositeFrame;
extern G__linked_taginfo G__GUIwrapperCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GUIwrapperCintLN_TGTextButton;
extern G__linked_taginfo G__GUIwrapperCintLN_TGVerticalFrame;
extern G__linked_taginfo G__GUIwrapperCintLN_TGMainFrame;
extern G__linked_taginfo G__GUIwrapperCintLN_TGTab;
extern G__linked_taginfo G__GUIwrapperCintLN_TGCheckButton;
extern G__linked_taginfo G__GUIwrapperCintLN_TCanvas;
extern G__linked_taginfo G__GUIwrapperCintLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__GUIwrapperCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GUIwrapperCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GUIwrapperCintLN_TH1F;
extern G__linked_taginfo G__GUIwrapperCintLN_TGLabel;
extern G__linked_taginfo G__GUIwrapperCintLN_TGNumberEntryField;
extern G__linked_taginfo G__GUIwrapperCintLN_AuxFrame;
extern G__linked_taginfo G__GUIwrapperCintLN_PMTwidget;
extern G__linked_taginfo G__GUIwrapperCintLN_MainFrame;
extern G__linked_taginfo G__GUIwrapperCintLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__GUIwrapperCintLN_process;
extern G__linked_taginfo G__GUIwrapperCintLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__GUIwrapperCintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GUIwrapperCintLN_GUIwrapper;

/* STUB derived class for protected member access */
